- name: Test Bookshelf deployment roles on localhost
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - python_build
    - clone_project
    - app_deps
    - cloud_sql
    - app_config
    - app_run
