---
- name: Ensure app config directory exists
  file:
    path: /home/kvbpac/projects/getting-started-python/7-gce
    state: directory
    mode: '0755'

- name: Generate config.py from Jinja template
  template:
    src: config.py.j2
    dest: /home/kvbpac/projects/getting-started-python/7-gce/config.py
    owner: kvbpac
    group: kvbpac
    mode: '0644'
- name: Change Flask app to listen on 0.0.0.0
  ansible.builtin.lineinfile:
    path: /home/kvbpac/projects/getting-started-python/7-gce/main.py
    regexp: '^\s*app\.run\(host=.*$'
    line: "    app.run(host='0.0.0.0', port=8080, debug=True)"
    owner: kvbpac
    group: kvbpac
    mode: '0644'
- name: Run model_cloudsql.py with Python 3.5.10 via pyenv
  become: yes
  become_user: kvbpac
  shell: |
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    python /home/kvbpac/projects/getting-started-python/7-gce/bookshelf/model_cloudsql.py
  args:
    executable: /bin/bash
- name: Fix werkzeug secure_filename import for compatibility
  replace:
    path: /home/kvbpac/projects/getting-started-python/7-gce/bookshelf/storage.py
    regexp: '^from werkzeug import secure_filename'
    replace: 'from werkzeug.utils import secure_filename'
